events {
    worker_connections 1024;
}

http {
    upstream nginx2_service {
        server nginx2:8082;
    }

    server {
        listen 8081;

        location / {
            proxy_pass http://nginx2_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
        }

        location /health {
            access_log off;
            return 200 "OK";
        }
    }
}




